Feature/novel
InterStory/InterStory pull request #45
Opened 2024-12-11 05:50 UTC by zeonzyeon

## #️⃣연관된 이슈

> #38 

## 📝작업 내용

> 
- 소설 기획서 작성
- 소설 수정
- 소설 상세 조회
- 소설 목록 조회
- 소설 삭제

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-12-11 06:30 UTC, Jindo-Dog requested changes

2024-12-11 06:30 UTC, Jindo-Dog commented on src/main/java/com/app/interstory/novel/service/NovelService.java
> +	@Transactional
생성과 조회에까지 어노테이션을 달 필요는 없어요

2024-12-11 06:30 UTC, Jindo-Dog commented on src/main/java/com/app/interstory/user/repository/CartItemRepository.java
> +	List<CartItem> findByUser(User user);
User로 찾지 않고 User_UserId로 찾는게 좋을 것 같아요

2024-12-11 07:43 UTC, afteryoon approved these changes, later dismissed

2024-12-11 08:32 UTC, greenapple-18 commented on src/main/java/com/app/interstory/novel/controller/EpisodeController.java
>  		@PathVariable Long episodeId,
userId는 세션에서 받아오는 게 더 안전할 것 같습니다.

2024-12-11 08:32 UTC, greenapple-18 commented on src/main/java/com/app/interstory/novel/controller/NovelController.java
> +		@RequestParam(name = "page", defaultValue = "1") int page
sort ENUM으로 만들어 둬서 사용하시면 될 것 같습니다.

2024-12-11 08:32 UTC, greenapple-18 commented on src/main/java/com/app/interstory/novel/controller/NovelController.java
> +		@RequestParam(name = "size", defaultValue = "10") int size
모두 파라미터로 넣기보단 일부는 body로 넘겨 dto를 사용하면 더 깔끔할 것 같습니다.

2024-12-11 08:32 UTC, Jindo-Dog requested changes

2024-12-11 08:32 UTC, Jindo-Dog commented on src/main/java/com/app/interstory/novel/repository/EpisodeLikeRepository.java
> +	void deleteByUserAndEpisode(@Param("user") User user, @Param("episode") Episode episode);
이곳도 userId로 조회하는게 좋을 것 같아요

2024-12-11 08:32 UTC, Jindo-Dog commented on src/main/java/com/app/interstory/novel/controller/EpisodeController.java
> +		@RequestBody Map<String, Long> body
body는 DTO를 따로 만들어서 가져와주세요

2024-12-11 08:32 UTC, Jindo-Dog commented on src/main/java/com/app/interstory/novel/controller/NovelController.java
> +		if (!"latest".equals(sort) && !"recommendations".equals(sort)) {
service로 넘길 수 있는 코드는 넘기는게 좋을 것 같아요

2024-12-11 08:32 UTC, Jindo-Dog commented on src/main/java/com/app/interstory/user/controller/CartController.java
> +	public ResponseEntity<List<CartItemResponseDTO>> getCartItems(@RequestBody Map<String, Long> request) {
body 부분은 DTO로 받아오면 좋을 것 같아요

2024-12-11 08:32 UTC, Jindo-Dog commented on src/main/java/com/app/interstory/user/repository/CartItemRepository.java
> +	List<CartItem> findByUserAndCartItemIdIn(User user, List<Long> cartItemIds);
두번째 세번째도 userId로 받아오면 좋을 것 같아요

2024-12-11 08:32 UTC, Jindo-Dog commented on src/main/java/com/app/interstory/user/service/CartService.java
> +		User user = userRepository.findById(userId)
사용하지 않는 변수 같아요

2024-12-12 00:20 UTC, afteryoon approved these changes

2024-12-12 00:40 UTC, greenapple-18 approved these changes

2024-12-12 01:12 UTC, Jindo-Dog approved these changes

2024-12-12 01:59 UTC, merged